### ISSUE TITLE
Add clusterctl support

### ISSUE THREAD

**Issue by christianang** [telekom/cluster-api-ipam-provider-in-cluster#33]
Now that clusterctl supports ipam providers via https://github.com/kubernetes-sigs/cluster-api/pull/7288, some work needs to be done in this provider to integrate with the clusterctl changes.

This [provider-contract doc](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/book/src/clusterctl/provider-contract.md) covers everything that needs to be done, but a summary of what I think needs to happen is:

* A GitHub release of this IPAM provider.
* The GitHub release contains:
  * metadata.yaml
  * ipam-provider.yaml (generated from ./config/default probably with some automation)
* Update metadata.yamll to adhere to the latest cluster-api contract version

There may be more that needs to be done, but this should be a good starting point.

/kind feature

**Comment by schrej** [comment]
Implemented and available as initial pre-release: https://github.com/telekom/cluster-api-ipam-provider-in-cluster/releases/tag/v0.1.0-alpha.1

Thanks for the summary!
