### ISSUE TITLE
Logs should include human readable timestamps

### ISSUE THREAD

**Issue by tylerschultz** [telekom/cluster-api-ipam-provider-in-cluster#69]
The current timestamps are integer format, which are helpful for log aggregators, but make it hard for humans to decipher. 

Proposal: Logs should be changed to ISO format, or should include both integer and ISO format timestamps.
```
2023-02-03T18:46:39Z
```

**Comment by tylerschultz** [comment]
We realized when browsing the zap logger configuration that this is already configurable.
Supplying the flag `--zap-time-encoding rfc3339` gave us what we want!

closing.

**Comment by tylerschultz** [comment]
We're back... It seems the best way to approach this would be to add something to the kustomize patches. We'll see what we can pull together.

**Comment by schrej** [comment]
Maybe we should just switch to k8s.io/klog/v2 instead of zap, since that's what CAPI is using as well.
