### ISSUE TITLE
IPAddresses should have their finalizer and owner refs restored if missing

### ISSUE THREAD

**Issue by tylerschultz** [telekom/cluster-api-ipam-provider-in-cluster#87]
In a scenario we've encountered, a backup/restore specifically, we see that the finalizer and owner refs are not restored. In the case they're missing, the controller should restore these owner references and finalizer. Currently, the finalizer is created when the controller creates the objects.

**Comment by schrej** [comment]
I agree. Might make sense to share the IPAddress reconciliation across providers.

**Comment by tylerschultz** [comment]
https://github.com/telekom/cluster-api-ipam-provider-in-cluster/pull/88 addresses this issue. 

@schrej I'm not sure if you feel that PR covers all that you'd like. I'm good with calling this issue done, but I'll leave it open for you to decide if there's more work to be done.
